# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterSplitter
                                 A QGIS plugin
 This plugin splits/clips raster into multiple files based on polugon features of a vector layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-07
        copyright            : (C) 2021 by Ram Shrestha
        email                : sendmail4ram@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterSplitter class from file RasterSplitter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .RasterSplitter import RasterSplitter
    return RasterSplitter(iface)
